import type { Question } from "./types/index.js";

export const PRE_SURVEY_QUESTIONS: Question[] = [
  {
    id: "age",
    label: "What is your age?",
    type: "radio",
    required: true,
    options: ["18 to 24", "25 to 34", "35 to 44", "45 to 54", "55 to 64", "65 to 74", "75 or older"],
  },
  {
    id: "education",
    label: "Education Level",
    type: "radio",
    required: true,
    options: ["High School or Lower", "Some College", "Bachelor's Degree", "Graduate Degree"],
  },
  {
    id: "employment",
    label: "Current Employment Status",
    type: "radio",
    required: true,
    options: ["Full-time", "Part-time", "Unemployed", "Student"],
  },
  {
    id: "prevCourses",
    label: "Have you previously taken any financial education courses?",
    type: "radio",
    required: true,
    options: ["Yes", "No"],
  },
  {
    id: "prevCoursesDesc",
    label: "If yes, please briefly describe what areas were covered:",
    type: "text",
    required: false,
    conditional: { id: "prevCourses", value: "Yes" },
  },
  {
    id: "careerUnderstanding",
    label: "How well do you understand the financial implications of your career choices?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["I don't understand at all", "Not Very Well", "Neutral", "Well", "Very Well"],
  },
  {
    id: "salaryConfidence",
    label: "How confident do you feel about negotiating your salary or discussing benefits?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["Not Confident", "Somewhat Confident", "Neutral", "Confident", "Very Confident"],
  },
  {
    id: "hasBudget",
    label: "Do you currently maintain a personal budget?",
    type: "radio",
    required: true,
    options: ["Yes", "No"],
  },
  {
    id: "budgetConfidence",
    label: "How confident are you in your ability to create and stay within a budget?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["Not Confident", "Somewhat Confident", "Neutral", "Confident", "Very Confident"],
  },
  {
    id: "hasSavings",
    label: "Do you currently have a savings account or plan for emergencies?",
    type: "radio",
    required: true,
    options: ["Yes", "No"],
  },
  {
    id: "savingsChallenges",
    label: "What do you find most challenging about saving money?",
    type: "text",
    required: false,
  },
  {
    id: "creditUnderstanding",
    label: "How would you rate your understanding of credit and how it works?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["No Understanding", "Limited Understanding", "Moderate Understanding", "Good Understanding", "Excellent Understanding"],
  },
  {
    id: "ficoScore",
    label: "What is your current FICO credit score?",
    type: "number",
    required: false,
  },
  {
    id: "hasDebt",
    label: "Do you currently have any unresolved debt?",
    type: "radio",
    required: true,
    options: ["Yes", "No"],
  },
  {
    id: "debtType",
    label: "If yes, what type of debt issues?",
    type: "text",
    required: false,
    conditional: { id: "hasDebt", value: "Yes" },
  },
  {
    id: "totalDebt",
    label: "How much is your total outstanding debt?",
    type: "number",
    required: false,
    conditional: { id: "hasDebt", value: "Yes" },
  },
  {
    id: "scamVictim",
    label: "Have you ever been a victim of a financial scam?",
    type: "radio",
    required: true,
    options: ["Yes", "No"],
  },
  {
    id: "learningGoals",
    label: "What do you hope to learn from this financial literacy class?",
    type: "text",
    required: false,
  },
  {
    id: "topicInterest",
    label: "Is there a specific topic you're particularly interested in learning about?",
    type: "text",
    required: false,
  },
];

export const POST_SURVEY_QUESTIONS: Question[] = [
  {
    id: "education",
    label: "Education Level",
    type: "radio",
    required: true,
    options: ["High School/GED/HI-SET", "Associates Degree", "Bachelors Degree", "Graduate Degree", "None of the above"],
  },
  {
    id: "employment",
    label: "Current Employment Status",
    type: "radio",
    required: true,
    options: ["Full-time", "Part-time", "Unemployed", "Student"],
  },
  {
    id: "overallUnderstanding",
    label: "How would you rate your overall understanding of financial concepts after taking this course?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["No Understanding", "Limited Understanding", "Moderate Understanding", "Good Understanding", "Excellent Understanding"],
  },
  {
    id: "careerUnderstanding",
    label: "How well do you understand the financial impact of your career choices?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["I don't understand the impact at all", "Not very well", "Neutral", "Well", "Very Well"],
  },
  {
    id: "salaryConfidence",
    label: "How confident do you feel now about possibly negotiating your salary or discussing benefits packages with your employer?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["Not confident", "Somewhat confident", "Neutral", "Confident", "Very confident"],
  },
  {
    id: "mostBeneficialTopics",
    label: "Which topics were the most beneficial for you?",
    type: "radio",
    required: true,
    options: ["Earning and Income", "Budgeting", "Credit and Debt Management", "Consumer Protection", "Other"],
  },
  {
    id: "mostBeneficialTopicsOther",
    label: "Please specify:",
    type: "text",
    required: false,
    conditional: { id: "mostBeneficialTopics", value: "Other" },
  },
  {
    id: "topicsMoreDepth",
    label: "Were there any topics you wish had been covered more in-depth?",
    type: "radio",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "topicsMoreDepthDesc",
    label: "Please specify:",
    type: "text",
    required: false,
    conditional: { id: "topicsMoreDepth", value: "Yes" },
  },
  {
    id: "hasBudget",
    label: "Do you currently maintain a personal budget after completing this course?",
    type: "radio",
    required: true,
    options: ["Yes", "No"],
  },
  {
    id: "hasSavingsPlan",
    label: "Do you have a savings plan in place now?",
    type: "radio",
    required: true,
    options: ["Yes", "No, but I now know how to create one", "No, and I do not understand how to create one"],
  },
  {
    id: "creditSteps",
    label: "Have you taken steps to improve your credit or debt management since attending the class?",
    type: "radio",
    required: true,
    options: ["Yes", "No"],
  },
  {
    id: "mostInteresting",
    label: "Which portion of the financial literacy program was the most interesting or important to you?",
    type: "text",
    required: false,
  },
  {
    id: "improvements",
    label: "What could we do to improve the course for the next group?",
    type: "text",
    required: false,
  },
  {
    id: "budgetConfidence",
    label: "How confident are you in your ability to create and stay within a budget?",
    type: "scale",
    scored: true,
    min: 1,
    max: 5,
    required: true,
    options: ["Not confident", "Somewhat confident", "Neutral", "Confident", "Very confident"],
  },
];

// Scored question IDs that exist in BOTH surveys — used for pre/post delta comparison
export const SCORED_QUESTION_IDS = [
  "careerUnderstanding",
  "salaryConfidence",
  "budgetConfidence",
];

export const SCORED_QUESTION_LABELS: Record<string, string> = {
  careerUnderstanding: "Career & Finance",
  salaryConfidence: "Salary Negotiation",
  budgetConfidence: "Budgeting",
};

// Keep SURVEY_QUESTIONS as an alias for backwards compatibility
export const SURVEY_QUESTIONS = PRE_SURVEY_QUESTIONS;